### ISSUE TITLE
Invalid action (Not Error)

### ISSUE THREAD

**Issue by SM64TASVideo** [mkdasher/SM64Lua#13]
![Screenshot 2024-06-21 230923](https://github.com/mkdasher/SM64Lua/assets/149284765/8730b0e5-08af-4177-b3dc-1cd75260392f)

Invalid Action Meaning: Holding Bowser And Release Bowser.

**Comment by MikeXander** [comment]
do not open multiple issues for the same error. Closed as duplicate

**Comment by SM64TASVideo** [comment]
> ![Screenshot 2024-06-21 230923](https://private-user-images.githubusercontent.com/149284765/341807579-8730b0e5-08af-4177-b3dc-1cd75260392f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzEzMDEsIm5iZiI6MTcxOTEzMTAwMSwicGF0aCI6Ii8xNDkyODQ3NjUvMzQxODA3NTc5LTg3MzBiMGU1LTA4YWYtNDE3Ny1iM2RjLTFjZDc1MjYwMzkyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwODIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmVkZjExMTUzY2UxNTI2YWRiY2EyZmUyNTJlMmY4ZmJlZTM0MDY2NDYyZmE2ZmRhNjFlMWJlMTBlMmFlMzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eZ3KW0K_Fy1C7cB4b33TvSSUqwqE7WiGHew3BSoF7mA)
> 
> Invalid Action Meaning: Holding Bowser And Release Bowser.

You mean isn't showing: Invalid Action = Holding Bowser, Release Bowser

**Comment by SM64TASVideo** [comment]
> do not open multiple issues for the same error. Closed as duplicate

You mean isn't showing: Invalid Action = Holding Bowser, Release Bowser

**Comment by SM64TASVideo** [comment]
> do not open multiple issues for the same error. Closed as duplicate

You're Nothing To fix the whole Input Lua script
No More Updated Lua Script
Do Not Closed duplicated
Have No Fix.
[DyllonStej Gaming] Backrooms64 Fix Whole Input Lua script
https://youtu.be/tpxJTOm7M88?feature=shared

Nothing Updated 👎
