### ISSUE TITLE
Backrooms64 Does Not Work in (SM64 LuaRedux), Still Unknown Action

### ISSUE THREAD

**Issue by SM64TASVideo** [mkdasher/SM64Lua#14]
![Screenshot 2024-06-22 093426](https://github.com/mkdasher/SM64Lua/assets/149284765/91356e63-6050-4fb0-ba85-c55a3aa8e2c1)

But Still Invalid Action

**Comment by MikeXander** [comment]
closing duplicate

**Comment by SM64TASVideo** [comment]
what you mean closing duplicate

**Comment by SM64TASVideo** [comment]
> closing duplicate

What you mean Closing duplicate?
Already Exists.

LuaRedux = Unknown Action

**Comment by SM64TASVideo** [comment]
> closing duplicate

What you meaning Fix Whole Input Lua Script, (LOTAD?):
https://youtu.be/tpxJTOm7M88?feature=shared

**Comment by SM64TASVideo** [comment]
> closing duplicate

NO

**Comment by SM64TASVideo** [comment]
> closing duplicate

You're Nothing To fix the whole Input Lua script
No More Updated Lua Script
Do Not Closed duplicated
Have No Fix.
[DyllonStej Gaming] Backrooms64 Fix Whole Input Lua script
https://youtu.be/tpxJTOm7M88?feature=shared

Nothing Updated 👎
